name: VS2022 (MSVC) Build and Test

on: [push, pull_request]

jobs:
  windows_msvc:
    runs-on: windows-latest
    name: VS2022 (MSVC)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup MSVC
        run: |
          echo "Using MSVC from Visual Studio 2022"
          
      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DPEELMESH_BUILD_PYTHON=ON -DPEELMESH_BUILD_TESTS=ON
          
      - name: Build
        run: |
          cmake --build build --config Release --target main
          
      - name: Run Tests
        run: |
          cd build
          ctest -C Release --output-on-failure

      - name: Upload Status
        uses: actions/upload-artifact@v4
        with:
          name: main_msvc
          path: build/Release/main.exe
          if-no-files-found: error