name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送 tag 时触发

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit  # 继承 secrets（如 GITHUB_TOKEN）

  release:
    name: Create GitHub Release
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Archive Source Code
        run: git archive --format=zip HEAD -o source.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-assets/**/*
            source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}